# Nixpacks configuration for Railway deployment
# This tells Railway how to build and run your application

[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
    "cd backend",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build phase completed'"
]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
