services:
  - type: web
    name: forward-resume-builder
    env: static
    buildCommand: cd frontend && npm ci && npm run build:prod
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable